<?php
/*
 * Settings metadata file
 * 
 * Author    Novalnet AG
 * Copyright (c) Novalnet
 * License   https://www.novalnet.de/payment-plugins/kostenlos/lizenz
 * 
 */
return array(
  'novalnet_product_activation_key' => array(
    'group_name' => 'Novalnet Preferences',
    'group' => 'novalnetgatewayform',
    'name' => 'novalnet_product_activation_key',
    'type' => 'String',
    'html_type' => 'text',
    'quick_form_type' => 'Element',
    'default' => '',
    'add' => '4.6',
    'title' =>  ts('Product activation key'),
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => ts('Enter Novalnet Product activation key'),
    'help_text' => NULL,
  ),

  'nn_vendor' => array(
    'group_name' => 'Novalnet Preferences',
    'group' => 'novalnetgatewayform',
    'name' => 'nn_vendor',
    'type' => 'String',
    'html_type' => 'text',
    'quick_form_type' => 'Element',
    'default' => '',
    'add' => '4.6',
    'title' =>  ts('Merchant ID'),
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => ts('Enter Novalnet merchant ID'),
    'help_text' => NULL,
  ),
  'nn_authcode' => array(
    'group_name' => 'Novalnet Preferences',
    'group' => 'novalnetgatewayform',
    'name' => 'nn_authcode',
    'type' => 'String',
    'html_type' => 'text',
    'quick_form_type' => 'Element',
    'default' => '',
    'add' => '4.6',
    'title' =>  ts('Authentication code'),
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => ts('Enter Novalnet authentication code'),
    'help_text' => NULL,
  ),
  'nn_product' => array(
    'group_name' => 'Novalnet Preferences',
    'group' => 'novalnetgatewayform',
    'name' => 'nn_product',
    'type' => 'String',
    'html_type' => 'text',
    'quick_form_type' => 'Element',
    'default' => '',
    'add' => '4.6',
    'title' =>  ts('Project ID'),
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => ts('Enter Novalnet project ID'),
    'help_text' => NULL,
  ),
  'nn_tariff' => array(
    'group_name' => 'Novalnet Preferences',
    'group' => 'novalnetgatewayform',
    'name' => 'nn_tariff',
    'type' => 'String',
    'html_type' => 'text',
    'quick_form_type' => 'Element',
    'default' => '',
    'add' => '4.6',
    'title' =>  ts('Tariff ID'),
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => ts('Enter Novalnet tariff ID'),
    'help_text' => NULL,
  ),
  'nn_password' => array(
    'group_name' => 'Novalnet Preferences',
    'group' => 'novalnetgatewayform',
    'name' => 'nn_password',
    'type' => 'String',
    'html_type' => 'text',
    'quick_form_type' => 'Element',
    'default' => '',
    'add' => '4.6',
    'title' =>  ts('Payment access key'),
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => ts('Enter the Novalnet payment access key'),
    'help_text' => NULL,
  ),
  'nn_subscription_tariff_id' => array(
    'group_name' => 'Novalnet Preferences',
    'group' => 'novalnetgatewayform',
    'name' => 'nn_subscription_tariff_id',
    'type' => 'String',
    'html_type' => 'text',
    'quick_form_type' => 'Element',
    'default' => '',
    'add' => '4.6',
    'title' =>  ts('Subscription Tariff ID'),
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => ts('Enter Novalnet subscription tariff ID'),
    'help_text' => NULL,
  ),
  'nn_subs_cancel_status' => array(
    'group_name' => 'Novalnet Preferences',
    'group' => 'novalnetgatewayform',
    'name' => 'nn_subs_cancel_status',
    'type' => 'String',
    'quick_form_type' => 'Select',
    'html_type' => 'Select',
    'html_attributes' => array(
      'class' => 'crm-select2',
    ),
    'add' => '4.6',
    'title' =>  ts('Cancellation status of subscription'),
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => NULL,
    'help_text' => NULL,
    'pseudoconstant' => array(
      'callback' => 'CRM_Admin_Form_Setting_NovalnetGatewayForm::getNovalnetStatus',
    ),
    ),
  'nn_referrer_id' => array(
    'group_name' => 'Novalnet Preferences',
    'group' => 'novalnetgatewayform',
    'name' => 'nn_referrer_id',
    'type' => 'String',
    'html_type' => 'text',
    'quick_form_type' => 'Element',
    'default' => '',
    'add' => '4.6',
    'title' =>  ts('Referrer ID'),
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => ts('Enter the referrer ID of the person/company who recommended you Novalnet'),
    'help_text' => NULL,
  ),
  'novalnet_pay_logo' => array(
    'group_name' => 'Novalnet Preferences',
    'group' => 'novalnetgatewayform',
    'name' => 'novalnet_pay_logo',
    'type' => 'Boolean',
    'html_type' => 'radio',
    'quick_form_type' => 'YesNo',
    'default' => '1',
    'add' => '4.6',
    'title' => ts('Display payment method logo'),
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => ts('The payment method logo will be displayed on the checkout page'),
    'help_text' => NULL,
  ),

    'novalnet_onhold_order_complete' => array(
    'group_name' => 'Novalnet Preferences',
    'group' => 'novalnetgatewayform',
    'name' => 'novalnet_onhold_order_complete',
    'type' => 'String',
    'quick_form_type' => 'Select',
    'html_type' => 'Select',
    'html_attributes' => array(
      'class' => 'crm-select2',
    ),
    'add' => '4.6',
    'title' => ts('Onhold order status'),
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => null,
    'help_text' => null,
    'pseudoconstant' => array(
      'callback' => 'CRM_Admin_Form_Setting_NovalnetGatewayForm::getNovalnetStatus',
    ),
  ),

    'novalnet_onhold_order_cancel' => array(
    'group_name' => 'Novalnet Preferences',
    'group' => 'novalnetgatewayform',
    'name' => 'novalnet_onhold_order_cancel',
    'type' => 'String',
    'quick_form_type' => 'Select',
    'html_type' => 'Select',
    'html_attributes' => array(
      'class' => 'crm-select2',
    ),
    'add' => '4.6',
    'title' => ts('Cancellation order status'),
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => null,
    'help_text' => null,
    'pseudoconstant' => array(
      'callback' => 'CRM_Admin_Form_Setting_NovalnetGatewayForm::getNovalnetStatus',
    ),
  ),

  'nn_callback_testmode' => array(
    'group_name' => 'Novalnet Preferences',
    'group' => 'novalnetgatewayform',
    'name' => 'nn_callback_testmode',
    'type' => 'Boolean',
    'html_type' => 'radio',
    'quick_form_type' => 'YesNo',
    'default' => '0',
    'add' => '4.6',
    'title' => ts('Deactivate IP address control (for test purpose only)'),
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => ts('This option will allow performing a manual execution. Please disable this option before setting your shop to LIVE mode, to avoid unauthorized calls from external parties (excl. Novalnet)
'),
    'help_text' => NULL,
  ),
  'nn_callback_sendmail' => array(
    'group_name' => 'Novalnet Preferences',
    'group' => 'novalnetgatewayform',
    'name' => 'nn_callback_sendmail',
    'type' => 'Boolean',
    'html_type' => 'radio',
    'quick_form_type' => 'YesNo',
    'default' => '0',
    'add' => '4.6',
    'title' => ts('Enable E-mail notification for callback'),
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => NULL,
    'help_text' => NULL,
  ),
   'nn_callback_frommail' => array(
    'group_name' => 'Novalnet Preferences',
    'group' => 'novalnetgatewayform',
    'name' => 'nn_callback_frommail',
    'type' => 'String',
    'html_type' => 'text',
    'quick_form_type' => 'Element',
    'default' => '',
    'add' => '4.6',
    'title' =>  ts('E-mail address (From)'),
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => ts('E-Mail address of the sender'),
    'help_text' => NULL,
  ),
    'nn_callback_tomail' => array(
    'group_name' => 'Novalnet Preferences',
    'group' => 'novalnetgatewayform',
    'name' => 'nn_callback_tomail',
    'type' => 'String',
    'html_type' => 'text',
    'quick_form_type' => 'Element',
    'default' => '',
    'add' => '4.6',
    'title' =>  ts('E-mail address (To)'),
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => ts('E-Mail address of the recipient'),
    'help_text' => NULL,
  ),
    'nn_callback_mailbcc' => array(
    'group_name' => 'Novalnet Preferences',
    'group' => 'novalnetgatewayform',
    'name' => 'nn_callback_mailbcc',
    'type' => 'String',
    'html_type' => 'text',
    'quick_form_type' => 'Element',
    'default' => '',
    'add' => '4.6',
    'title' =>  ts('E-mail address (Bcc)'),
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => ts('E-Mail address of the recipient for BCC'),
    'help_text' => NULL,
  ),
    'nn_notify_url' => array(
    'group_name' => 'Novalnet Preferences',
    'group' => 'novalnetgatewayform',
    'name' => 'nn_notify_url',
    'type' => 'String',
    'html_type' => 'text',
    'quick_form_type' => 'Element',
    'default' => '',
    'add' => '4.6',
    'title' =>  ts('Notification URL'),
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => ts('The notification URL is used to keep your database/system actual and synchronizes with the Novalnet transaction status.'),
    'help_text' => NULL,
  ),
    'nn_inv_testmode' => array(
    'group_name' => 'Novalnet Preferences',
    'group' => 'novalnetgatewayform',
    'name' => 'nn_inv_testmode',
    'type' => 'Boolean',
    'html_type' => 'radio',
    'quick_form_type' => 'YesNo',
    'default' => '0',
    'add' => '4.6',
    'title' => ts('Enable test mode'),
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => ts('The payment will be processed in the test mode therefore amount for this transaction will not be charged'),
    'help_text' => NULL,
  ),
    'nn_inv_duedate' => array(
    'group_name' => 'Novalnet Preferences',
    'group' => 'novalnetgatewayform',
    'name' => 'nn_inv_duedate',
    'type' => 'String',
    'html_type' => 'text',
    'quick_form_type' => 'Element',
    'default' => '',
    'add' => '4.6',
    'title' =>  ts('Payment due date (in days)'),
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => ts('Enter the number of days after which the payment should be processed (must be between 2 and 14 days)'),
    'help_text' => NULL,
  ),

    'nn_invoice_manualamount' => array(
    'group_name' => 'Novalnet Preferences',
    'group' => 'novalnetgatewayform',
    'name' => 'nn_invoice_manualamount',
    'type' => 'String',
    'html_type' => 'text',
    'quick_form_type' => 'Element',
    'default' => '',
    'add' => '4.6',
    'title' =>  ts('Set a limit for on-hold transaction (in minimum unit of currency. E.g. enter 100 which is equal to 1.00)'),
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => ts('In case the order amount exceeds mentioned limit, the transaction will be set on hold till your confirmation of transaction'),
    'help_text' => NULL,
  ),
    'novalnet_invoice_cont_status' => array(
    'group_name' => 'Novalnet Preferences',
    'group' => 'novalnetgatewayform',
    'name' => 'novalnet_invoice_cont_status',
    'type' => 'String',
    'quick_form_type' => 'Select',
    'html_type' => 'Select',
    'html_attributes' => array(
      'class' => 'crm-select2',
    ),
    'add' => '4.6',
    'title' =>  ts('Order completion status'),
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => NULL,
    'help_text' => NULL,
    'pseudoconstant' => array(
      'callback' => 'CRM_Admin_Form_Setting_NovalnetGatewayForm::getNovalnetStatus',
    ),
  ),
    'novalnet_invoice_cont_cb_status' => array(
    'group_name' => 'Novalnet Preferences',
    'group' => 'novalnetgatewayform',
    'name' => 'novalnet_invoice_cont_cb_status',
    'type' => 'String',
    'quick_form_type' => 'Select',
    'html_type' => 'Select',
    'html_attributes' => array(
      'class' => 'crm-select2',
    ),
    'add' => '4.6',
    'title' =>  ts('Callback order status'),
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => NULL,
    'help_text' => NULL,
    'pseudoconstant' => array(
      'callback' => 'CRM_Admin_Form_Setting_NovalnetGatewayForm::getNovalnetStatus',
    ),
  ),

    'novalnet_invoice_guarantee' => array(
    'group_name' => 'Novalnet Preferences',
    'group' => 'novalnetgatewayform',
    'name' => 'novalnet_invoice_guarantee',
    'type' => 'Boolean',
    'html_type' => 'radio',
    'quick_form_type' => 'YesNo',
    'default' => '0',
    'add' => '4.6',
    'title' =>  ts('Enable payment guarantee'),
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => NULL,
    'help_text' => NULL,
  ),

    'novalnet_invoice_guarantee_status' => array(
    'group_name' => 'Novalnet Preferences',
    'group' => 'novalnetgatewayform',
    'name' => 'novalnet_invoice_guarantee_status',
    'type' => 'String',
    'quick_form_type' => 'Select',
    'html_type' => 'Select',
    'html_attributes' => array(
      'class' => 'crm-select2',
    ),
    'add' => '4.6',
    'title' =>  ts('Order status for the pending payment'),
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => NULL,
    'help_text' => NULL,
    'pseudoconstant' => array(
      'callback' => 'CRM_Admin_Form_Setting_NovalnetGatewayForm::getNovalnetStatus',
    ),
  ),
    'novalnet_invoice_guarantee_amt' => array(
    'group_name' => 'Novalnet Preferences',
    'group' => 'novalnetgatewayform',
    'name' => 'novalnet_invoice_guarantee_amt',
    'type' => 'String',
    'html_type' => 'text',
    'quick_form_type' => 'Element',
    'default' => '',
    'add' => '4.6',
    'title' =>  ts('Minimum order amount (in minimum unit of currency. E.g. enter 100 which is equal to 1.00)'),
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => ts('This setting will override the default setting made in the minimum order amount. Note that amount should be in the range of 9,99 EUR'),
    'help_text' => NULL,
  ),
    'novalnet_invoice_force_guarantee' => array(
    'group_name' => 'Novalnet Preferences',
    'group' => 'novalnetgatewayform',
    'name' => 'novalnet_invoice_force_guarantee',
    'type' => 'Boolean',
    'html_type' => 'radio',
    'quick_form_type' => 'YesNo',
    'default' => '0',
    'add' => '4.6',
    'title' => ts('Force Non-Guarantee payment'),
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => ts('If the payment guarantee is activated (True), but the above mentioned requirements are not met, the payment should be processed as non-guarantee payment.'),
    'help_text' => NULL,
  ),
    'novalnet_invoice_notify' => array(
    'group_name' => 'Novalnet Preferences',
    'group' => 'novalnetgatewayform',
    'name' => 'novalnet_invoice_notify',
    'type' => 'String',
    'html_type' => 'text',
    'quick_form_type' => 'Element',
    'default' => '',
    'add' => '4.6',
    'title' =>  ts('Notification for the buyer'),
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => ts('The entered text will be displayed on the checkout page'),
    'help_text' => NULL,
  ),
    'nn_prepayment_testmode' => array(
    'group_name' => 'Novalnet Preferences',
    'group' => 'novalnetgatewayform',
    'name' => 'nn_prepayment_testmode',
    'type' => 'Boolean',
    'html_type' => 'radio',
    'quick_form_type' => 'YesNo',
    'default' => '0',
    'add' => '4.6',
    'title' => ts('Enable test mode'),
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => ts('The payment will be processed in the test mode therefore amount for this transaction will not be charged'),
    'help_text' => NULL,
  ),
    'novalnet_prepayment_cont_status' => array(
    'group_name' => 'Novalnet Preferences',
    'group' => 'novalnetgatewayform',
    'name' => 'novalnet_prepayment_cont_status',
    'type' => 'String',
    'quick_form_type' => 'Select',
    'html_type' => 'Select',
    'html_attributes' => array(
      'class' => 'crm-select2',
    ),
    'add' => '4.6',
    'title' =>  ts('Order completion status'),
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => NULL,
    'help_text' => NULL,
    'pseudoconstant' => array(
      'callback' => 'CRM_Admin_Form_Setting_NovalnetGatewayForm::getNovalnetStatus',
    ),
  ),
    'novalnet_prepayment_cont_cb_status' => array(
    'group_name' => 'Novalnet Preferences',
    'group' => 'novalnetgatewayform',
    'name' => 'novalnet_prepayment_cont_cb_status',
    'type' => 'String',
    'quick_form_type' => 'Select',
    'html_type' => 'Select',
    'html_attributes' => array(
      'class' => 'crm-select2',
    ),
    'add' => '4.6',
    'title' =>  ts('Callback order status'),
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => NULL,
    'help_text' => NULL,
    'pseudoconstant' => array(
      'callback' => 'CRM_Admin_Form_Setting_NovalnetGatewayForm::getNovalnetStatus',
    ),
  ),
    'novalnet_prepayment_notify' => array(
    'group_name' => 'Novalnet Preferences',
    'group' => 'novalnetgatewayform',
    'name' => 'novalnet_prepayment_notify',
    'type' => 'String',
    'html_type' => 'text',
    'quick_form_type' => 'Element',
    'default' => '',
    'add' => '4.6',
    'title' =>  ts('Notification for the buyer'),
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => ts('The entered text will be displayed on the checkout page'),
    'help_text' => NULL,
  ),
    'nn_cc_testmode' => array(
    'group_name' => 'Novalnet Preferences',
    'group' => 'novalnetgatewayform',
    'name' => 'nn_cc_testmode',
    'type' => 'Boolean',
    'html_type' => 'radio',
    'quick_form_type' => 'YesNo',
    'default' => '0',
    'add' => '4.6',
    'title' => ts('Enable test mode'),
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => ts('The payment will be processed in the test mode therefore amount for this transaction will not be charged'),
    'help_text' => NULL,
  ),
    'nn_cc_secure_active' => array(
    'group_name' => 'Novalnet Preferences',
    'group' => 'novalnetgatewayform',
    'name' => 'nn_cc_secure_active',
    'type' => 'Boolean',
    'html_type' => 'radio',
    'quick_form_type' => 'YesNo',
    'default' => '0',
    'add' => '4.6',
    'title' => ts('Enable 3D secure'),
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => ts('The 3D-Secure will be activated for credit cards. The issuing bank prompts the buyer for a password what, in turn, help to prevent a fraudulent payment. It can be used by the issuing bank as evidence that the buyer is indeed their card holder. This is intended to help decrease a risk of charge-back.'),
    'help_text' => NULL,
  ),
    'nn_cc_force_secure_active' => array(
    'group_name' => 'Novalnet Preferences',
    'group' => 'novalnetgatewayform',
    'name' => 'nn_cc_force_secure_active',
    'type' => 'Boolean',
    'html_type' => 'radio',
    'quick_form_type' => 'YesNo',
    'default' => '0',
    'add' => '4.6',
    'title' => ts('Force 3D secure on predefined conditions'),
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => NULL,
    'help_text' => NULL,
  ),

    'nn_cc_manualamount' => array(
    'group_name' => 'Novalnet Preferences',
    'group' => 'novalnetgatewayform',
    'name' => 'nn_cc_manualamount',
    'type' => 'String',
    'html_type' => 'text',
    'quick_form_type' => 'Element',
    'default' => '',
    'add' => '4.6',
    'title' =>  ts('Set a limit for on-hold transaction (in minimum unit of currency. E.g. enter 100 which is equal to 1.00)'),
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => ts('In case the order amount exceeds mentioned limit, the transaction will be set on hold till your confirmation of transaction.'),
    'help_text' => NULL,
  ),

    'novalnet_cc_cont_status' => array(
    'group_name' => 'Novalnet Preferences',
    'group' => 'novalnetgatewayform',
    'name' => 'novalnet_cc_cont_status',
    'type' => 'String',
    'quick_form_type' => 'Select',
    'html_type' => 'Select',
    'html_attributes' => array(
      'class' => 'crm-select2',
    ),
    'add' => '4.6',
    'title' =>  ts('Order completion status'),
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => NULL,
    'help_text' => NULL,
    'pseudoconstant' => array(
      'callback' => 'CRM_Admin_Form_Setting_NovalnetGatewayForm::getNovalnetStatus',
    ),
  ),
    'nn_cc_amexlogo_active' => array(
    'group_name' => 'Novalnet Preferences',
    'group' => 'novalnetgatewayform',
    'name' => 'nn_cc_amexlogo_active',
    'type' => 'Boolean',
    'html_type' => 'radio',
    'quick_form_type' => 'YesNo',
    'default' => '0',
    'add' => '4.6',
    'title' => ts('Display AMEX logo'),
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => ts('Display AMEX logo in checkout page'),
    'help_text' => NULL,
  ),
    'nn_cc_cartasilogo_active' => array(
    'group_name' => 'Novalnet Preferences',
    'group' => 'novalnetgatewayform',
    'name' => 'nn_cc_cartasilogo_active',
    'type' => 'Boolean',
    'html_type' => 'radio',
    'quick_form_type' => 'YesNo',
    'default' => '0',
    'add' => '4.6',
    'title' => ts('Display CartaSi logo'),
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => ts('Display CartaSi logo in checkout page'),
    'help_text' => NULL,
  ),
    'nn_cc_maestrologo_active' => array(
    'group_name' => 'Novalnet Preferences',
    'group' => 'novalnetgatewayform',
    'name' => 'nn_cc_maestrologo_active',
    'type' => 'Boolean',
    'html_type' => 'radio',
    'quick_form_type' => 'YesNo',
    'default' => '0',
    'add' => '4.6',
    'title' => ts('Display Maestro logo'),
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => ts('Display Maestro logo in checkout page'),
    'help_text' => NULL,
  ),

    'nn_cc_css_settings_label' => array(
    'group_name' => 'Novalnet Preferences',
    'group' => 'novalnetgatewayform',
    'name' => 'nn_cc_css_settings_label',
    'type' => 'String',
    'html_type' => 'text',
    'quick_form_type' => 'Element',
    'default' => '',
    'add' => '4.6',
    'title' =>  ts('Label'),
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => NULL,
    'help_text' => NULL,
  ),
    'nn_cc_css_settings_input' => array(
    'group_name' => 'Novalnet Preferences',
    'group' => 'novalnetgatewayform',
    'name' => 'nn_cc_css_settings_input',
    'type' => 'String',
    'html_type' => 'text',
    'quick_form_type' => 'Element',
    'default' => '',
    'add' => '4.6',
    'title' =>  ts('Input'),
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => NULL,
    'help_text' => NULL,
  ),
    'nn_cc_css_settings_css_text' => array(
    'group_name' => 'Novalnet Preferences',
    'group' => 'novalnetgatewayform',
    'name' => 'nn_cc_css_settings_css_text',
    'type' => 'String',
    'html_type' => 'text',
    'quick_form_type' => 'Element',
    'default' => '',
    'add' => '4.6',
    'title' =>  ts('CSS Text'),
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => NULL,
    'help_text' => NULL,
  ),
    'novalnet_cc_notify' => array(
    'group_name' => 'Novalnet Preferences',
    'group' => 'novalnetgatewayform',
    'name' => 'novalnet_cc_notify',
    'type' => 'String',
    'html_type' => 'text',
    'quick_form_type' => 'Element',
    'default' => '',
    'add' => '4.6',
    'title' =>  ts('Notification for the buyer'),
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => ts('The entered text will be displayed on the checkout page'),
    'help_text' => NULL,
  ),
    'nn_sepa_testmode' => array(
    'group_name' => 'Novalnet Preferences',
    'group' => 'novalnetgatewayform',
    'name' => 'nn_sepa_testmode',
    'type' => 'Boolean',
    'html_type' => 'radio',
    'quick_form_type' => 'YesNo',
    'default' => '0',
    'add' => '4.6',
    'title' => ts('Enable test mode'),
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => ts('The payment will be processed in the test mode therefore amount for this transaction will not be charged'),
    'help_text' => NULL,
  ),
    'nn_sepa_due_date' => array(
    'group_name' => 'Novalnet Preferences',
    'group' => 'novalnetgatewayform',
    'name' => 'nn_sepa_due_date',
    'type' => 'String',
    'html_type' => 'text',
    'quick_form_type' => 'Element',
    'default' => '',
    'add' => '4.6',
    'title' =>  ts('SEPA payment duration (in days)'),
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => ts('Enter the number of days after which the payment should be processed (must be between 2 and 14 days)'),
    'help_text' => NULL,
  ),
    'nn_sepa_manualamount' => array(
    'group_name' => 'Novalnet Preferences',
    'group' => 'novalnetgatewayform',
    'name' => 'nn_sepa_manualamount',
    'type' => 'String',
    'html_type' => 'text',
    'quick_form_type' => 'Element',
    'default' => '',
    'add' => '4.6',
    'title' =>  ts('Set a limit for on-hold transaction (in minimum unit of currency. E.g. enter 100 which is equal to 1.00)'),
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => ts('In case the order amount exceeds mentioned limit, the transaction will be set on hold till your confirmation of transaction.'),
    'help_text' => NULL,
  ),
    'novalnet_sepa_cont_status' => array(
    'group_name' => 'Novalnet Preferences',
    'group' => 'novalnetgatewayform',
    'name' => 'novalnet_sepa_cont_status',
    'type' => 'String',
    'quick_form_type' => 'Select',
    'html_type' => 'Select',
    'html_attributes' => array(
      'class' => 'crm-select2',
    ),
    'add' => '4.6',
    'title' =>  ts('Order completion status'),
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => NULL,
    'help_text' => NULL,
    'pseudoconstant' => array(
      'callback' => 'CRM_Admin_Form_Setting_NovalnetGatewayForm::getNovalnetStatus',
    ),
  ),
    'novalnet_sepa_guarantee' => array(
    'group_name' => 'Novalnet Preferences',
    'group' => 'novalnetgatewayform',
    'name' => 'novalnet_sepa_guarantee',
    'type' => 'Boolean',
    'html_type' => 'radio',
    'quick_form_type' => 'YesNo',
    'default' => '0',
    'add' => '4.6',
    'title' =>  ts('Enable payment guarantee'),
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => NULL,
    'help_text' => NULL,
  ),
    'novalnet_sepa_guarantee_status' => array(
    'group_name' => 'Novalnet Preferences',
    'group' => 'novalnetgatewayform',
    'name' => 'novalnet_sepa_guarantee_status',
    'type' => 'String',
    'quick_form_type' => 'Select',
    'html_type' => 'Select',
    'html_attributes' => array(
      'class' => 'crm-select2',
    ),
    'add' => '4.6',
    'title' =>  ts('Order status for the pending payment'),
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => NULL,
    'help_text' => NULL,
    'pseudoconstant' => array(
      'callback' => 'CRM_Admin_Form_Setting_NovalnetGatewayForm::getNovalnetStatus',
    ),
  ),
    'novalnet_sepa_guarantee_amt' => array(
    'group_name' => 'Novalnet Preferences',
    'group' => 'novalnetgatewayform',
    'name' => 'novalnet_sepa_guarantee_amt',
    'type' => 'String',
    'html_type' => 'text',
    'quick_form_type' => 'Element',
    'default' => '',
    'add' => '4.6',
    'title' =>  ts('Minimum order amount (in minimum unit of currency. E.g. enter 100 which is equal to 1.00)'),
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => ts('This setting will override the default setting made in the minimum order amount. Note that amount should be in the range of 9,99 EUR'),
    'help_text' => NULL,
  ),
    'novalnet_sepa_force_guarantee' => array(
    'group_name' => 'Novalnet Preferences',
    'group' => 'novalnetgatewayform',
    'name' => 'novalnet_sepa_force_guarantee',
    'type' => 'Boolean',
    'html_type' => 'radio',
    'quick_form_type' => 'YesNo',
    'default' => '0',
    'add' => '4.6',
    'title' => ts('Force Non-Guarantee payment'),
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => ts('If the payment guarantee is activated (True), but the above mentioned requirements are not met, the payment should be processed as non-guarantee payment.'),
    'help_text' => NULL,
  ),
    'novalnet_sepa_notify' => array(
    'group_name' => 'Novalnet Preferences',
    'group' => 'novalnetgatewayform',
    'name' => 'novalnet_sepa_notify',
    'type' => 'String',
    'html_type' => 'text',
    'quick_form_type' => 'Element',
    'default' => '',
    'add' => '4.6',
    'title' =>  ts('Notification for the buyer'),
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => ts('The entered text will be displayed on the checkout page'),
    'help_text' => NULL,
  ),  
    'nn_paypal_testmode' => array(
    'group_name' => 'Novalnet Preferences',
    'group' => 'novalnetgatewayform',
    'name' => 'nn_paypal_testmode',
    'type' => 'Boolean',
    'html_type' => 'radio',
    'quick_form_type' => 'YesNo',
    'default' => '0',
    'add' => '4.6',
    'title' => ts('Enable test mode'),
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => ts('The payment will be processed in the test mode therefore amount for this transaction will not be charged'),
    'help_text' => NULL,
  ),
    'nn_paypal_manualamount' => array(
    'group_name' => 'Novalnet Preferences',
    'group' => 'novalnetgatewayform',
    'name' => 'nn_paypal_manualamount',
    'type' => 'String',
    'html_type' => 'text',
    'quick_form_type' => 'Element',
    'default' => '',
    'add' => '4.6',
    'title' =>  ts('Set a limit for on-hold transaction (in minimum unit of currency. E.g. enter 100 which is equal to 1.00)'),
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => ts('In case the order amount exceeds mentioned limit, the transaction will be set on hold till your confirmation of transaction. In order to use this option you must have billing agreement option enabled in your PayPal account. Please contact your account manager at PayPal.'),
    'help_text' => NULL,
  ),
    'novalnet_paypal_pending_status' => array(
    'group_name' => 'Novalnet Preferences',
    'group' => 'novalnetgatewayform',
    'name' => 'novalnet_paypal_pending_status',
    'type' => 'String',
    'quick_form_type' => 'Select',
    'html_type' => 'Select',
    'html_attributes' => array(
      'class' => 'crm-select2',
    ),
    'add' => '4.6',
    'title' =>  ts('Order status for the pending payment'),
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => NULL,
    'help_text' => NULL,
    'pseudoconstant' => array(
      'callback' => 'CRM_Admin_Form_Setting_NovalnetGatewayForm::getNovalnetStatus',
    ),
  ),
    'novalnet_paypal_cont_status' => array(
    'group_name' => 'Novalnet Preferences',
    'group' => 'novalnetgatewayform',
    'name' => 'novalnet_paypal_cont_status',
    'type' => 'String',
    'quick_form_type' => 'Select',
    'html_type' => 'Select',
    'html_attributes' => array(
      'class' => 'crm-select2',
    ),
    'add' => '4.6',
    'title' =>  ts('Order completion status'),
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => NULL,
    'help_text' => NULL,
    'pseudoconstant' => array(
      'callback' => 'CRM_Admin_Form_Setting_NovalnetGatewayForm::getNovalnetStatus',
    ),
  ),
    'novalnet_paypal_notify' => array(
    'group_name' => 'Novalnet Preferences',
    'group' => 'novalnetgatewayform',
    'name' => 'novalnet_paypal_notify',
    'type' => 'String',
    'html_type' => 'text',
    'quick_form_type' => 'Element',
    'default' => '',
    'add' => '4.6',
    'title' =>  ts('Notification for the buyer'),
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => ts('The entered text will be displayed on the checkout page'),
    'help_text' => NULL,
  ),  
    'nn_ideal_testmode' => array(
    'group_name' => 'Novalnet Preferences',
    'group' => 'novalnetgatewayform',
    'name' => 'nn_ideal_testmode',
    'type' => 'Boolean',
    'html_type' => 'radio',
    'quick_form_type' => 'YesNo',
    'default' => '0',
    'add' => '4.6',
    'title' => ts('Enable test mode'),
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => ts('The payment will be processed in the test mode therefore amount for this transaction will not be charged'),
    'help_text' => NULL,
  ),
    'novalnet_ideal_cont_status' => array(
    'group_name' => 'Novalnet Preferences',
    'group' => 'novalnetgatewayform',
    'name' => 'novalnet_ideal_cont_status',
    'type' => 'String',
    'quick_form_type' => 'Select',
    'html_type' => 'Select',
    'html_attributes' => array(
      'class' => 'crm-select2',
    ),
    'add' => '4.6',
    'title' =>  ts('Order completion status'),
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => NULL,
    'help_text' => NULL,
    'pseudoconstant' => array(
      'callback' => 'CRM_Admin_Form_Setting_NovalnetGatewayForm::getNovalnetStatus',
    ),
  ),
    'novalnet_ideal_notify' => array(
    'group_name' => 'Novalnet Preferences',
    'group' => 'novalnetgatewayform',
    'name' => 'novalnet_ideal_notify',
    'type' => 'String',
    'html_type' => 'text',
    'quick_form_type' => 'Element',
    'default' => '',
    'add' => '4.6',
    'title' =>  ts('Notification for the buyer'),
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => ts('The entered text will be displayed on the checkout page'),
    'help_text' => NULL,
  ),  
    'nn_instant_testmode' => array(
    'group_name' => 'Novalnet Preferences',
    'group' => 'novalnetgatewayform',
    'name' => 'nn_instant_testmode',
    'type' => 'Boolean',
    'html_type' => 'radio',
    'quick_form_type' => 'YesNo',
    'default' => '0',
    'add' => '4.6',
    'title' => ts('Enable test mode'),
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => ts('The payment will be processed in the test mode therefore amount for this transaction will not be charged'),
    'help_text' => NULL,
  ),
    'novalnet_instant_cont_status' => array(
    'group_name' => 'Novalnet Preferences',
    'group' => 'novalnetgatewayform',
    'name' => 'novalnet_instant_cont_status',
    'type' => 'String',
    'quick_form_type' => 'Select',
    'html_type' => 'Select',
    'html_attributes' => array(
      'class' => 'crm-select2',
    ),
    'add' => '4.6',
    'title' =>  ts('Order completion status'),
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => NULL,
    'help_text' => NULL,
    'pseudoconstant' => array(
      'callback' => 'CRM_Admin_Form_Setting_NovalnetGatewayForm::getNovalnetStatus',
    ),
  ),
    'novalnet_instant_notify' => array(
    'group_name' => 'Novalnet Preferences',
    'group' => 'novalnetgatewayform',
    'name' => 'novalnet_instant_notify',
    'type' => 'String',
    'html_type' => 'text',
    'quick_form_type' => 'Element',
    'default' => '',
    'add' => '4.6',
    'title' =>  ts('Notification for the buyer'),
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => ts('The entered text will be displayed on the checkout page'),
    'help_text' => NULL,
  ),    
    'nn_eps_testmode' => array(
    'group_name' => 'Novalnet Preferences',
    'group' => 'novalnetgatewayform',
    'name' => 'nn_eps_testmode',
    'type' => 'Boolean',
    'html_type' => 'radio',
    'quick_form_type' => 'YesNo',
    'default' => '0',
    'add' => '4.6',
    'title' => ts('Enable test mode'),
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => ts('The payment will be processed in the test mode therefore amount for this transaction will not be charged'),
    'help_text' => NULL,
  ),
    'novalnet_eps_cont_status' => array(
    'group_name' => 'Novalnet Preferences',
    'group' => 'novalnetgatewayform',
    'name' => 'novalnet_eps_cont_status',
    'type' => 'String',
    'quick_form_type' => 'Select',
    'html_type' => 'Select',
    'html_attributes' => array(
      'class' => 'crm-select2',
    ),
    'add' => '4.6',
    'title' =>  ts('Order completion status'),
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => NULL,
    'help_text' => NULL,
    'pseudoconstant' => array(
      'callback' => 'CRM_Admin_Form_Setting_NovalnetGatewayForm::getNovalnetStatus',
    ),
  ),
    'novalnet_eps_notify' => array(
    'group_name' => 'Novalnet Preferences',
    'group' => 'novalnetgatewayform',
    'name' => 'novalnet_eps_notify',
    'type' => 'String',
    'html_type' => 'text',
    'quick_form_type' => 'Element',
    'default' => '',
    'add' => '4.6',
    'title' =>  ts('Notification for the buyer'),
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => ts('The entered text will be displayed on the checkout page'),
    'help_text' => NULL,
  ),  
    'nn_giropay_testmode' => array(
    'group_name' => 'Novalnet Preferences',
    'group' => 'novalnetgatewayform',
    'name' => 'nn_giropay_testmode',
    'type' => 'Boolean',
    'html_type' => 'radio',
    'quick_form_type' => 'YesNo',
    'default' => '0',
    'add' => '4.6',
    'title' => ts('Enable test mode'),
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => ts('The payment will be processed in the test mode therefore amount for this transaction will not be charged'),
    'help_text' => NULL,
  ),
    'novalnet_giropay_cont_status' => array(
    'group_name' => 'Novalnet Preferences',
    'group' => 'novalnetgatewayform',
    'name' => 'novalnet_giropay_cont_status',
    'type' => 'String',
    'quick_form_type' => 'Select',
    'html_type' => 'Select',
    'html_attributes' => array(
      'class' => 'crm-select2',
    ),
    'add' => '4.6',
    'title' =>  ts('Order completion status'),
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => NULL,
    'help_text' => NULL,
    'pseudoconstant' => array(
      'callback' => 'CRM_Admin_Form_Setting_NovalnetGatewayForm::getNovalnetStatus',
    ),
  ),
    'novalnet_giropay_notify' => array(
    'group_name' => 'Novalnet Preferences',
    'group' => 'novalnetgatewayform',
    'name' => 'novalnet_giropay_notify',
    'type' => 'String',
    'html_type' => 'text',
    'quick_form_type' => 'Element',
    'default' => '',
    'add' => '4.6',
    'title' =>  ts('Notification for the buyer'),
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => ts('The entered text will be displayed on the checkout page'),
    'help_text' => NULL,
  ),   
);
